name: softbd
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  circular_countdown_timer: ^0.2.3
  flutter_timer_countdown: ^1.0.7
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/
  fonts:
    - family: Noto Serif Bengali
      fonts:
        - asset: fonts/NotoSerifBengali_ExtraCondensed-Regular.ttf
        - asset: fonts/NotoSerifBengali-Regular.ttf

